apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fpc5t6gf0-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fpc5t6gf0-python 
  name: fpc5t6gf0-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fpc5t6gf0-python 
